apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeflix-catalog-admin-api
  labels:
    app: codeflix-catalog-admin-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeflix-catalog-admin-api
  template:
    metadata:
      labels:
        app: codeflix-catalog-admin-api
    spec:
      containers:
      - name: codeflix-catalog-admin-api
        image: epscavalcante/codeflix-catalog-admin-api:latest
        imagePullPolicy: Always
        args: [ "dist/main" ]
        envFrom:
          - configMapRef:
              name: codeflix-catalog-admin-api-configmap
          - secretRef:
              name: codeflix-catalog-admin-api-secret
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
