version: '3'

services:
    app:
        build: ./node
        container_name: catalog-admin-app
        command: ./.docker/start.sh
        environment:
            - DB_VENDOR=sqlite
            - DB_HOST=":memory:"
            - DB_LOGGING=false
            - DB_AUTO_LOAD_MODELS=true
        ports:
            - 3000:3000
        volumes:
            - ..:/home/node/app

    db:
        image: mysql:8.0.30-debian
        container_name: catalog-admin-db
        environment:
            - MYSQL_DATABASE=catalog
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/data:/var/lib/mysql:delegated
        security_opt:
            - seccomp:unconfined

    db_tests:
        image: mysql:8.0.30-debian
        container_name: catalog-admin-db-tests
        environment:
        - MYSQL_DATABASE=catalog
        - MYSQL_ROOT_PASSWORD=root
        tmpfs: /var/lib/mysql
        security_opt:
        - seccomp:unconfined
