version: '3'

services:
    app:
        build: ./node
        container_name: catalog-admin-app
        ports:
            - 3000:3000
        volumes:
            - ..:/home/node/app

    adminer:
        image: adminer:4-standalone
        container_name: catalog-admin-adminer
        restart: always
        ports:
        - 8080:8080

    db:
        image: mysql:8.0.30-debian
        container_name: catalog-admin-db
        environment:
            - MYSQL_DATABASE=catalog
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/data:/var/lib/mysql:delegated
        security_opt:
            - seccomp:unconfined

    # db_tests:
    #     image: mysql:8.0.30-debian
    #     container_name: catalog-admin-db-tests
    #     environment:
    #     - MYSQL_DATABASE=catalog
    #     - MYSQL_ROOT_PASSWORD=root
    #     tmpfs: /var/lib/mysql
    #     security_opt:
    #     - seccomp:unconfined
